# Generated by Django 4.0.3 on 2022-03-25 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Consumer Loans', 'Consumer Loans'), ('House Loans', 'House Loans'), ('Mortgage Loans', 'Mortgage Loans')], max_length=14)),
                ('amount', models.CharField(max_length=200000, validators=[django.core.validators.MinLengthValidator(1000), sofia_bank.common_files.validators.validate_only_numbers])),
                ('period', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), sofia_bank.common_files.validators.validate_only_numbers])),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type')},
            },
        ),
    ]
