# Generated by Django 4.0.3 on 2022-03-30 15:01

import django.core.validators
from django.db import migrations, models
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banksavings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloans',
            name='amount',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(4), sofia_bank.common_files.validators.validate_only_numbers]),
        ),
        migrations.AlterField(
            model_name='bankloans',
            name='period',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(1), sofia_bank.common_files.validators.validate_only_numbers]),
        ),
    ]
