# Generated by Django 4.0.3 on 2022-03-31 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bankloans_amount_alter_bankloans_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloans',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bankloans',
            name='period',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
    ]
