# Generated by Django 4.0.3 on 2022-03-31 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bankloans_amount_alter_bankloans_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloans',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200000), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='banksavings',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
