# Generated by Django 4.0.3 on 2022-04-05 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bankloans_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmAndBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('neighborhood', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('street', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('branches_and_atms', models.CharField(choices=[('ATMs', 'ATMs'), ('Branches', 'Branches')], max_length=8)),
                ('open_on_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
