# Generated by Django 4.0.3 on 2022-04-05 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_atmandbranches_bank_or_atm_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmandbranches',
            name='id',
        ),
        migrations.AlterField(
            model_name='atmandbranches',
            name='bank_or_atm_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('happy', models.BooleanField()),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('bank_or_atm_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.atmandbranches')),
            ],
        ),
    ]
