# Generated by Django 4.0.3 on 2022-04-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_exchangerates_currency_alter_feedback_happy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
    ]
