# Generated by Django 4.0.3 on 2022-03-22 14:00

import django.core.validators
from django.db import migrations, models
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), sofia_bank.common_files.validators.validate_only_letters])),
                ('middle_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(30), sofia_bank.common_files.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), sofia_bank.common_files.validators.validate_only_letters])),
                ('egn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='EGN')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(9)])),
                ('date_of_birth', models.DateField(validators=[sofia_bank.common_files.validators.validate_age])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=11, null=True)),
            ],
        ),
    ]
