# Generated by Django 4.0.3 on 2022-03-23 20:04

import django.core.validators
from django.db import migrations, models
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_id_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), sofia_bank.common_files.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
