# Generated by Django 4.0.3 on 2022-03-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofiabankuser',
            name='loan_amount',
            field=models.FloatField(default=0),
        ),
    ]
