# Generated by Django 4.0.3 on 2022-03-31 14:01

import django.core.validators
from django.db import migrations, models
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sofiabankuser_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='egn',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), sofia_bank.common_files.validators.validate_only_numbers], verbose_name='EGN'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(8), sofia_bank.common_files.validators.validate_only_numbers]),
        ),
    ]
