# Generated by Django 4.0.3 on 2022-04-13 08:17

import django.core.validators
from django.db import migrations, models
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_egn_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(8), sofia_bank.common_files.validators.validate_only_numbers]),
        ),
    ]
