# Generated by Django 4.0.3 on 2022-04-15 14:25

import django.core.validators
from django.db import migrations, models
import sofia_bank.common_files.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='egn',
            field=models.CharField(error_messages={'blank': 'You already registered!'}, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), sofia_bank.common_files.validators.validate_only_numbers], verbose_name='EGN'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email with this data is already taken.'}, max_length=254, unique=True),
        ),
    ]
